# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ds4p23
author: Corrado Caudek
logo: logo.png
copyright: "2023"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  latex_documents:
    targetname: book.tex

# Bibtex config
bibtex_reference_style: author_year
bibtex_bibfiles: "references.bib"

# Information about where the book exists on the web
repository:
  url: https://github.com/ccaudek/ds4psy_2023 # Online location of your book
  path_to_book: docs/ # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

footer_text: Created by <a href="https://ccaudek.github.io/caudeklab/">Corrado Caudek</a> using <a href="https://jupyterbook.org/">Jupyter Book</a>.

# Launch button settings
launch_buttons:
  notebook_interface: "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  colab_url: ""
  binderhub_url: ""
  thebe: false  # Add a thebe button to pages (requires the repository to run on Binder)


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "images/increasing.png"
  google_analytics_id: "G-VMXNE4BCDL"
  baseurl: "https://github.com/ccaudek/ds4psy_2023"
  use_repository_button     : false
  use_edit_page_button      : false
  use_issues_button         : false 
  baseurl: https://ccaudek.github.io/ds4psy_2023  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false

sphinx:
    config:
      html_theme_options:
        use_download_button: true
        repository_url: "https://github.com/ccaudek/ds4psy_2023"
        use_issues_button: false
        use_repository_button: false
        use_edit_page_button: false


